### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by ChannyAzar** [G5/g5_prom_rails#2]
Hi,

From your documentation I can see a list of metrics:

Metrics include:

_sidekiq_processed_ Counter for jobs processed.
_sidekiq_failed_ Counter for jobs failed.
_sidekiq_retry_ Gauge for current retries length.
_sidekiq_queued_ Gauge for current queue length. The label queue is applied to allow per-queue analysis.
_sidekiq_job_seconds,sidekiq_job_seconds_sum,sidekiq_job_seconds_count_ Histogram for job execution time. The label job_name is applied, and will be identical to the Ruby class name of the job (e.g. MyImportantWorker).

I used your gem, but I can see only last metric:

```
# TYPE sidekiq_job_seconds histogram
# HELP sidekiq_job_seconds job running time in seconds
```

Am I missing something? do I need some custom code?

**Comment by dpetersen** [comment]
Hey, thanks for contacting me. I was not properly watching this repo in Github and wasn't getting any notifications.

I'm assuming the output you've posted above is from the `/metrics` path? What if you hit `/probe`, do you see additional metrics? This is a deficiency in my README, I think. This is an open source gem, but honestly I didn't know that anybody else was attempting to use it.

The reasoning behind the two endpoints is discussed briefly in [the configuration section of the README](https://github.com/G5/g5_prom_rails#configuration), and probably not in enough detail. Most of our applications run behind a load balancer and there are multiple instances. In-memory metrics like counters will have different values for each instance of the Rails app, as different traffic goes to different processes. But we also want to track some metrics that are application-wide, like how many Person rows are in the database, for instance. It wouldn't matter which instance was hit by the load balancer when the metrics were scraped, they're all connected to the same database.

The `/probe` path comes from the blackbox exporter. We're using Kubernetes, and [the reference Prometheus configuration](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L173-L203) for Kubernetes integration uses the `/metrics` and `/probe` endpoints to differentiate between these two types of metrics.

FYI, I'm realizing now in production that the way I'm tracking sidekiq job timing is not working for apps with quick sidekiq jobs. The app I wrote this engine for has extremely long-running jobs, and so it worked fine. I may make some changes to the way the `sidekiq_job_seconds*` metrics are collected. The other Sidekiq-related metrics should stay the same.
