### ISSUE TITLE
Prometheus-client 0.9.0

### ISSUE THREAD

**Issue by Bastes** [G5/g5_prom_rails#3]
Hi,

We're using your gem to monitor our server, and arrived at a point where we need gauges we can increment ; this is not possible with `prometheus-client` `0.7.0` but it is with with `0.9.0`.

Is there anybody still maintaining this gem, and maybe planning on upgrading? :sweat_smile:

**Comment by dpetersen** [comment]
Oh, increment would be handy. Thanks for filing the issue. I have good news and bad news. I just released `g5_prom_rails` `0.3.3`, which allows `prometheus-client` `< 0.10.0`. The `0.10.0` version has breaking changes that would require changes in `g5_prom_rails`'s metrics initializers, and updates everywhere in our internal code that uses it and has custom metrics.

Which brings me to the bad news: this gem isn't maintained any longer. We are using it internally a fair amount, but are planning on moving our applications to [discourse/prometheus_exporter](https://github.com/discourse/prometheus_exporter). That gem isn't exactly a drop-in replacement and it requires a little more work to get running, but it has far more users and functionality.

**Comment by Bastes** [comment]
Well, thanks for the reply and the suggestion :) we ended up forking and
updating on our side to experiment and so far it seems to be working, but
we'll definitely look into discourse/prometheus_exporter.

Cheers :)

Michel Belleville
